Models/ErrorViewModel.cs
namespace WeatherSite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ForcastWeather.cs
 namespace WeatherSite.Models
{
    public class ForcastWeather
    {
        public Forcast Forcast { get; set; }
    }

    public class Forcast
    {
        public List<ForcastDay> ForcastDays { get; set; }
    }

    public class ForcastDay
    {
        public string Date { get; set; }
        public string Date_Epoch { get; set; }
        public Day Day { get; set; }
        public Astro Astro { get; set; }
        public List<Hour> Hours { get; set; }
    }

    public class Day
    {
        public double Maxtemp_c {  get; set; }
        public double Mintemp_c { get; set; }
        public double Maxtemp_f { get; set; }
        public double Mintemp_f { get; set; }
        public double Avgtemp_f { get; set; }
        public double Avgtemp_c { get; set; }
        public double Maxwind_mph { get; set; }
        public double Maxwind_kph { get; set; }
        public double Totalprecip_mm { get; set; }
        public double Totalprecip_in { get; set; }
        public double Totalsnow_cm { get; set; }
        public Condition Condition { get; set; }

    }

    public class Astro
    {
        public string Sunrise { get; set; }
        public string Sunset { get; set; }
        public string Moonrise { get; set; }
        public string Moonset { get; set; }
        public string Moon_Phase { get; set; }
        public int Moon_Illumination { get; set; }
        public int Is_Moon_Up { get; set; }
        public int Is_Sun_Up { get; set; }
    }

    public class Hour
    {
        public long Time_Epoch { get; set; }
        public string Time {  get; set; }
        public double Tempo_c {  get; set; }
        public double Tempo_f { get; set; }
        public int Is_Day { get; set; }
        public Condition Condition { get; set; }
    }

    
}

Models/RealTimeWeather.cs
namespace WeatherSite.Models
{
    public class WeatherData
    {
        public Location Location { get; set; }
        public Current Current { get; set; }
    }
    

    public class Location
    {
        public string Name { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string Tz_id { get; set; }
        public long Localtime_epoch { get; set; }
        public string Localtime { get; set; }
    }

    public class Current
    {
        public long Last_updated_epoch { get; set; }
        public string Last_updated { get; set; }
        public double Temp_c { get; set; }
        public double Temp_f { get; set; }
        public int Is_day { get; set; }
        public Condition Condition { get; set; }
        public double Wind_mph { get; set; }
        public double Wind_kph { get; set; }
        public int Wind_degree { get; set; }
        public string Wind_dir { get; set; }
        public double Pressure_mb { get; set; }
        public double Pressure_in { get; set; }
        public double Precip_mm { get; set; }
        public double Precip_in { get; set; }
        public int Humidity { get; set; }
        public int Cloud { get; set; }
        public double Feelslike_c { get; set; }
        public double Feelslike_f { get; set; }
        public double Vis_km { get; set; }
        public double Vis_miles { get; set; }
        public double Uv { get; set; }
        public double Gust_mph { get; set; }
        public double Gust_kph { get; set; }
    }

    public class Condition
    {
        public string Text { get; set; }
        public string Icon { get; set; }
        public int Code { get; set; }
    }
}

Controllers/RealTimeWeatherController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherSite.Data;
using WeatherSite.Models;

namespace WeatherSite.Controllers
{
    public class RealTimeWeatherController : Controller
    {
        WeatherData weather;
        WeatherSite.Data.RealTimeWeatherAPI api = new RealTimeWeatherAPI();
        
        public IActionResult Index()
        {
            weather = api.GetData("Paris"); //Default Parameter
            return View(weather);
        }

        [HttpPost]
        public IActionResult Index(string cityName)
        {
            if (cityName.Contains(" "))
            {
                cityName = cityName.Replace(" ", "%20");
            }

            weather = api.GetData(cityName);

            return View(weather);
        }

    }
}

Views/RealTimeWeather/Index.cshtml
@model WeatherSite.Models.WeatherData;
@{
    ViewData["Title"] = "Real Time Weather";
}

<div>
    <div class="row d-flex justify-content-center align-items-center">
    @using (Html.BeginForm("Index", "RealTimeWeather", FormMethod.Post))
    {
        <div class="row g-3">
            <div class="col-auto">
                <label for="lblCity" class="form-label">Enter City Name:</label>
            </div>
            <div class="col-auto">
                <input type="text" class="form-control" id="inputCity" name="CityName" placeholder="e.g. Paris">
            </div>

            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-3">Search</button>
            </div>
        </div>
    }
    </div>

    <section class="vh-100">
        <div class="container py-5 h-100">

            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-8 col-lg-6 col-xl-4">

                    <div class="card" style="color: #4B515D; border-radius: 35px;">
                        <div class="card-body p-4">

                            <div class="d-flex">
                                <h6 class="flex-grow-1">@Model.Location.Name</h6>
                                <h6>Local Time: @Model.Location.Localtime</h6>
                            </div>

                            <div class="d-flex flex-column text-center mt-5 mb-4">
                                <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> @Model.Current.Temp_c °C</h6>
                                <span class="small" style="color: #868B94">@Model.Current.Condition.Text</span>
                            </div>

                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1" style="font-size: 1rem;">
                                    <div>
                                        <div>
                                            <i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Feels Like: @Model.Current.Feelslike_c °C</span>
                                        </div>
                                        <i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1">
                                            Wind Speed: @Model.Current.Wind_kph @Model.Current.Wind_dir
                                        </span>
                                    </div>

                                    <div>
                                        <i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Precipitaion: @Model.Current.Precip_mm mm</span>
                                    </div>
                                    <div>
                                        <i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Humidity: @Model.Current.Humidity %</span>
                                    </div>
                                    <div>
                                        <i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Pressure: @Model.Current.Pressure_mb mb</span>
                                    </div>
                                </div>
                                <div>
                                    <img src="@Model.Current.Condition.Icon"
                                         width="100px">
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

        </div>
    </section>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="RealTimeWeather" asp-action="Index">WeatherSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RealTimeWeather" asp-action="Index">RealTimeWeather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://www.linkedin.com/in/TJ-Mothokho">About Me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WeatherSite - <a href="https://www.linkedin.com/in/TJ-Mothokho">About Me</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>